version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - backend_network
    restart: unless-stopped

networks:
  backend_network:
    driver: bridge